### ISSUE TITLE
GUI work division

### ISSUE THREAD

**Issue by lokeshveeramacheneni** [lokeshveeramacheneni/Software-Development-Project#35]
![SDP](https://user-images.githubusercontent.com/48586221/69871305-bcd86b80-12b2-11ea-8a68-fd18acae544e.png)
This is the GUI required and there are 3 requirements:
1. First row consists of 2 buttons to start the ROSCORE, and to bring up the launch file. These buttons must be green or red based on the status. Assigned to @lokeshveeramacheneni 
2. Second task is display all the nodes in the launch file if they are running it is green else it is red. Assigned to @Vanargh 
3. Third task is to put a drop down which has all the topics presently published and then on selection of particular topic the data must come on the next display (rectangle in this diagram). Assigned to @ZuhaKarim

**Comment by ZuhaKarim** [comment]
I am able to get rostopic list from bash and access it in JS file and in the console the output is fine but in the dropdown, there is some problem in the display working on it.
