### ISSUE TITLE
Repetitive Node check

### ISSUE THREAD

**Issue by lokeshveeramacheneni** [lokeshveeramacheneni/Software-Development-Project#42]
@Vanargh  Try to complete this issue by this weekend, then next week we can sit on testing

**Comment by Vanargh** [comment]
The new updated Phase_1.html has been modified and the problem is solved

**Comment by lokeshveeramacheneni** [comment]
It is not working even though  I killed the node manually to check. It not going down
@Vanargh testing is required
![after killing nodes](https://user-images.githubusercontent.com/48586221/72201963-6f771e80-345a-11ea-8a39-957bd40f268b.png)
![before killing nodes](https://user-images.githubusercontent.com/48586221/72201964-6f771e80-345a-11ea-8743-85d1e81eceea.png)
![kill nodes](https://user-images.githubusercontent.com/48586221/72201965-6f771e80-345a-11ea-8fe8-960f579c3498.png)
